# Generated by Django 4.2.9 on 2024-01-16 12:03

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CredlyOrganization",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("uuid", models.UUIDField(help_text="Unique credly organization ID.", unique=True)),
                ("name", models.CharField(help_text="Name of credly organization.", max_length=255)),
                ("api_key", models.CharField(help_text="Credly organization API bearer secret.", max_length=255)),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
