# Generated by Django 4.2.7 on 2024-01-26 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credly_badges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credlyorganization',
            name='api_key',
            field=models.CharField(help_text='Credly API shared secret for organization.', max_length=255),
        ),
        migrations.AlterField(
            model_name='credlyorganization',
            name='name',
            field=models.CharField(help_text='Organization display name.', max_length=255),
        ),
        migrations.AlterField(
            model_name='credlyorganization',
            name='uuid',
            field=models.UUIDField(help_text='Unique organization ID.', unique=True),
        ),
        migrations.CreateModel(
            name='BadgeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(help_text='Unique badge template ID.', unique=True)),
                ('name', models.CharField(help_text='Badge template name.', max_length=255)),
                ('state', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('draft', 'Draft'), ('inactive', 'Inactive')], default='inactive', help_text='State of the badge template.', max_length=255)),
                ('organization', models.ForeignKey(help_text='Organization of the badge template.', on_delete=django.db.models.deletion.CASCADE, to='credly_badges.credlyorganization')),
            ],
        ),
    ]
