# Generated by Django 4.2.7 on 2024-02-06 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
        ('credly_badges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credlyorganization',
            name='api_key',
            field=models.CharField(help_text='Credly API shared secret for organization.', max_length=255),
        ),
        migrations.AlterField(
            model_name='credlyorganization',
            name='name',
            field=models.CharField(help_text='Organization display name.', max_length=255),
        ),
        migrations.AlterField(
            model_name='credlyorganization',
            name='uuid',
            field=models.UUIDField(help_text='Unique organization ID.', unique=True),
        ),
        migrations.CreateModel(
            name='CredlyBadgeTemplate',
            fields=[
                ('badgetemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='badges.badgetemplate')),
                ('organization', models.ForeignKey(help_text='Organization of the credly badge template.', on_delete=django.db.models.deletion.CASCADE, to='credly_badges.credlyorganization')),
            ],
            options={
                'abstract': False,
            },
            bases=('badges.badgetemplate',),
        ),
    ]
