# Generated by Django 3.2.20 on 2024-03-20 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0026_alter_usercredential_credential_content_type'),
        ('credly_badges', '0003_credlybadgetemplate_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredlyBadge',
            fields=[
                ('usercredential_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='credentials.usercredential')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('credentials.usercredential',),
        ),
    ]
