# Generated by Django 3.2.20 on 2024-03-27 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0026_alter_usercredential_credential_content_type'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('badges', '0001_initial'),
        ('credly_badges', '0005_auto_20240327_1118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CredlyBadgeCredential',
            new_name='CredlyBadge',
        ),
    ]
