# Generated by Django 3.2.16 on 2023-02-09 18:36

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0025_change_usercredentialdateoverride_date'),
        ('verifiable_credentials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiableCredentialIssuance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('issuer_did', models.TextField()),
                ('processed', models.BooleanField(default=False)),
                ('user_credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vc_issues', to='credentials.usercredential')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
