# Generated by Django 3.2.16 on 2023-02-16 15:08

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0025_change_usercredentialdateoverride_date'),
        ('verifiable_credentials', '0002_verifiablecredentialissuance'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuanceLine',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('processed', models.BooleanField(default=False, help_text='Completeness indicator')),
                ('issuer_id', models.CharField(help_text='Issuer DID', max_length=255)),
                ('storage_id', models.CharField(help_text='Target storage identifier', max_length=128)),
                ('user_credential', models.ForeignKey(help_text='Related Open edX learner credential', on_delete=django.db.models.deletion.PROTECT, related_name='vc_issues', to='credentials.usercredential')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='verifiablecredentialissuance',
            name='user_credential',
        ),
        migrations.DeleteModel(
            name='IssuanceConfiguration',
        ),
        migrations.DeleteModel(
            name='VerifiableCredentialIssuance',
        ),
    ]
