# Generated by Django 3.2.16 on 2023-02-17 15:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('verifiable_credentials', '0003_auto_20230216_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuanceline',
            name='holder_id',
            field=models.CharField(default='did:example:12345', help_text='Holder DID', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuanceline',
            name='subject_id',
            field=models.CharField(blank=True, help_text='Subject DID (if not provided corresponds to "Holder")', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issuanceline',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
