# Generated by Django 3.2.16 on 2023-02-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifiable_credentials', '0004_auto_20230217_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuanceline',
            name='holder_id',
            field=models.CharField(blank=True, help_text='Holder DID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issuanceline',
            name='subject_id',
            field=models.CharField(blank=True, help_text='Subject DID (if not provided corresponds to "Holder ID")', max_length=255, null=True),
        ),
    ]
