# Generated by Django 3.2.16 on 2023-02-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifiable_credentials', '0005_auto_20230218_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuanceline',
            name='status_index',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
