# Generated by Django 3.2.18 on 2023-03-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifiable_credentials', '0006_issuanceline_status_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuanceline',
            name='status',
            field=models.CharField(choices=[('awarded', 'awarded'), ('revoked', 'revoked')], default='awarded', help_text="Keeps track on a corresponding user credential's status", max_length=255),
        ),
        migrations.AlterField(
            model_name='issuanceline',
            name='status_index',
            field=models.PositiveIntegerField(help_text='Defines a position in the Status List sequence', null=True),
        ),
    ]
