# Generated by Django 3.2.18 on 2023-03-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("verifiable_credentials", "0006_auto_20230305_1318"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issuanceline",
            old_name="data_model",
            new_name="data_model_id",
        ),
    ]
