# Generated by Django 3.2.18 on 2023-03-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifiable_credentials', '0007_auto_20230312_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuanceline',
            name='holder_id',
        ),
        migrations.AlterField(
            model_name='issuanceline',
            name='data_model_id',
            field=models.CharField(blank=True, help_text='Verifiable credential specification to use', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issuanceline',
            name='subject_id',
            field=models.CharField(default='change-me', help_text='Verifiable credential subject DID', max_length=255),
            preserve_default=False,
        ),
    ]
