# Generated by Django 3.2.18 on 2023-03-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifiable_credentials', '0008_auto_20230312_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuanceline',
            name='status',
            field=models.CharField(choices=[('awarded', 'awarded'), ('revoked', 'revoked')], default='awarded', help_text="Keeps track on a corresponding user credential's status", max_length=255),
        ),
        migrations.AddField(
            model_name='issuanceline',
            name='status_index',
            field=models.PositiveIntegerField(help_text='Defines a position in the Status List sequence', null=True),
        ),
        migrations.AlterField(
            model_name='issuanceline',
            name='data_model_id',
            field=models.CharField(blank=True, choices=[('vc', 'Verifiable Credentials Data Model v1.1'), ('obv3', 'Open Badges Specification v3.0')], help_text='Verifiable credential specification to use', max_length=255, null=True),
        ),
    ]
