# Generated by Django 3.2.18 on 2023-03-22 11:33

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('verifiable_credentials', '0009_auto_20230320_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuanceConfiguration',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('enabled', models.BooleanField(default=False)),
                ('issuer_id', models.CharField(help_text='Issuer DID', max_length=255, primary_key=True, serialize=False)),
                ('issuer_key', models.JSONField(help_text='Issuer secret key. See: https://w3c-ccg.github.io/did-method-key/#ed25519-x25519')),
                ('issuer_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
