# Generated by Django 3.2.18 on 2023-03-23 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0025_change_usercredentialdateoverride_date'),
        ('verifiable_credentials', '0010_issuanceconfiguration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuanceconfiguration',
            options={'ordering': ['enabled']},
        ),
        migrations.AlterField(
            model_name='issuanceline',
            name='status',
            field=models.CharField(blank=True, help_text="Keeps track on a corresponding user credential's status", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issuanceline',
            name='status_index',
            field=models.PositiveIntegerField(blank=True, help_text='Defines a position in the Status List sequence', null=True),
        ),
        migrations.AlterField(
            model_name='issuanceline',
            name='user_credential',
            field=models.ForeignKey(blank=True, help_text='Related Open edX learner credential', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vc_issues', to='credentials.usercredential'),
        ),
    ]
