# Generated by Django 3.2.18 on 2023-04-05 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifiable_credentials', '0010_data_create_default_issuers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuanceconfiguration',
            options={'ordering': ('enabled', 'created')},
        ),
        migrations.AlterModelOptions(
            name='issuanceline',
            options={'ordering': ('created',)},
        ),
        migrations.AlterUniqueTogether(
            name='issuanceline',
            unique_together={('issuer_id', 'status_index')},
        ),
    ]
