# Generated by Django 4.2.7 on 2024-02-06 14:24

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_active', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(help_text='Unique badge template ID.', unique=True)),
                ('name', models.CharField(help_text='Badge template name.', max_length=255)),
                ('type', models.CharField(default='openedx', max_length=255)),
                ('status', models.CharField(choices=[('active', 'active'), ('archived', 'archived'), ('draft', 'draft'), ('revoked', 'revoked')], help_text='Status of the badge template.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Badge template description.', null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='badge_templates/icons')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
