# Generated by Django 4.2.10 on 2024-02-11 16:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("badges", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="badgetemplate",
            name="status",
        ),
        migrations.RemoveField(
            model_name="badgetemplate",
            name="type",
        ),
        migrations.AddField(
            model_name="badgetemplate",
            name="origin",
            field=models.CharField(blank=True, help_text="Badge template type.", max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="badgetemplate",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, help_text="Unique badge template ID.", unique=True),
        ),
    ]
