# Generated by Django 4.2.16 on 2024-12-18 13:09

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("badges", "0002_accredibleapiconfig_accrediblebadge_accrediblegroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badgetemplate",
            name="icon",
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to="badge_templates/icons"),
        ),
        migrations.AlterField(
            model_name="badgetemplate",
            name="state",
            field=model_utils.fields.StatusField(
                choices=[("draft", "draft"), ("active", "active"), ("archived", "archived")],
                default="draft",
                help_text="Credly badge template state (auto-managed).",
                max_length=100,
                no_check_for_status=True,
                null=True,
            ),
        ),
    ]
