# Generated by Django 4.2.10 on 2024-02-25 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("badges", "0002_remove_badgetemplate_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BadgeRequirement",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "event_type",
                    models.CharField(
                        help_text='Public signal type. Use namespaced types, e.g: "org.openedx.learning.student.registration.completed.v1"',
                        max_length=255,
                    ),
                ),
                (
                    "effect",
                    models.CharField(
                        choices=[("award", "award"), ("revoke", "revoke")],
                        default="award",
                        help_text="Defines how this requirement contributes to badge earning.",
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="Provide more details if needed.", null=True)),
                (
                    "template",
                    models.ForeignKey(
                        help_text="Badge template this requirement serves for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="badges.badgetemplate",
                    ),
                ),
            ],
        ),
    ]
