# Generated by Django 4.2.10 on 2024-02-25 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("badges", "0003_badgerequirement"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataRule",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "path",
                    models.CharField(
                        help_text='Public signal\'s data payload nested property path, e.g: "user.pii.username".',
                        max_length=255,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text='Expected value for the nested property, e.g: "cucumber1997".', max_length=255
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        help_text="Parent requirement for this data rule.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="badges.badgerequirement",
                    ),
                ),
            ],
        ),
    ]
