# Generated by Django 4.2.10 on 2024-03-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badges", "0004_datarule"),
    ]

    operations = [
        migrations.AddField(
            model_name="datarule",
            name="operator",
            field=models.CharField(
                choices=[("eq", "=")],
                default="eq",
                help_text="Expected value comparison operator. https://docs.python.org/3/library/operator.html",
                max_length=32,
                verbose_name="action",
            ),
        ),
        migrations.AlterField(
            model_name="datarule",
            name="path",
            field=models.CharField(
                help_text='Public signal\'s data payload nested property path, e.g: "user.pii.username".',
                max_length=255,
                verbose_name="key path",
            ),
        ),
        migrations.AlterField(
            model_name="datarule",
            name="value",
            field=models.CharField(
                help_text='Expected value for the nested property, e.g: "cucumber1997".',
                max_length=255,
                verbose_name="expected value",
            ),
        ),
    ]
