# Generated by Django 4.2.10 on 2024-03-03 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("credentials", "0028_alter_historicalprogramcompletionemailconfiguration_options"),
        ("badges", "0005_datarule_operator_alter_datarule_path_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BadgeProgress",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(max_length=255)),
                (
                    "credential",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="credentials.usercredential",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fulfillment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("progress", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="badges.badgeprogress")),
                (
                    "requirement",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="badges.badgerequirement"),
                ),
            ],
        ),
    ]
