# Generated by Django 4.2.10 on 2024-03-03 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("badges", "0006_badgeprogress_fulfillment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="badgeprogress",
            options={"verbose_name_plural": "badge progress records"},
        ),
        migrations.AddField(
            model_name="badgeprogress",
            name="template",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="badges.badgetemplate"
            ),
        ),
        migrations.AlterField(
            model_name="fulfillment",
            name="requirement",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="badges.badgerequirement"
            ),
        ),
    ]
