# Generated by Django 3.2.20 on 2025-07-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0021_alter_credlyorganization_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgetemplate',
            name='icon',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='badge_templates/icons'),
        ),
    ]
